social/base/urls.py
from django.urls import path
from .views import (
    PostListView, PostDetailView,
    PostCreateView, PostUpdateView,
    PostDeleteView, postLike
)
from . import views

app_name = 'base'

urlpatterns = [
    # Post
    #  path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('', PostListView.as_view(), name='home'),
    path('post/<slug:slug>/<int:year>/<int:month>/<int:day>/<int:pk>', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    # Like posts
    path('post-like/<int:pk>', views.postLike, name='post-like'),
]

social/notification/urls.py
from django.urls import path
from notification.views import showNotifications

app_name = 'notification'

urlpatterns = [
    path('notifications/', showNotifications, name='notifications')
]

social/social/urls.py
from django.conf import settings
from django.contrib.auth.models import User
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.pagination import PageNumberPagination
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from rest_framework import routers, serializers, viewsets
from base.base_api import views as base_views
from sending_email_app import views as mail_views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from rest_framework_simplejwt.views import TokenVerifyView

# class StandardResultsSetPagination(PageNumberPagination):
#     page_size = 2
#     page_size_query_param = 'page_size'

class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


class UserViewSet(viewsets.ModelViewSet):
    # pagination_class = StandardResultsSetPagination
    queryset = User.objects.all()
    serializer_class = UserSerializer


router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'posts', base_views.PostViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace='base')),
    path('', include('users.urls', namespace='users')),
    path('', include('notification.urls', namespace='notification')),
    path('api/v1/', include(router.urls)),
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('sendmail/', mail_views.sending_mail_to_all, name="sendmail"),

    # Profile/Registration/Login/Logout
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),

    # Change password
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name='registration/change_password_form.html',
                                                                    success_url=reverse_lazy('change_password_done')),
                                                                    name='change_password'),
    path('change-password/done', auth_views.PasswordChangeDoneView.as_view(template_name='registration/change_password_done.html'),
                                                                            name='change_password_done'),
]

if settings.DEBUG:
    # Media
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # Debug Toolbar
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
        ]

social/base/models.py
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from ckeditor.fields import RichTextField


class Post(models.Model):
    """ Post model """
    title = models.CharField(max_length=100)
    content = RichTextField(blank=True, null=True)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=250, null=True,
                            unique_for_date='date_posted')
    likes = models.ManyToManyField(User, related_name='post_like', blank=True)
    
    def total_likes(self):
        return self.likes.count()

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(self.title)
        return super(Post, self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("base:post-detail", kwargs={'slug': self.slug,
                                                   'year': self.date_posted.year,
                                                   'month': self.date_posted.month,
                                                   'day': self.date_posted.day,
                                                   'pk': self.pk})
        
    def __str__(self) -> str:
        return f'{self.author}: {self.title}'
    
    class Meta:
        default_related_name = 'posts'
        ordering = ['-date_posted']
        indexes = [
            models.Index(fields=['-date_posted', 'slug'])
        ]
    

class Comment(models.Model):
    """ Comment model """
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        default_related_name = 'comments'
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]

    def __str__(self) -> str:
        return f'Comment by {self.username} on {self.post}' 

social/notification/models.py
from django.db import models
from django.contrib.auth.models import User


class Notification(models.Model):
    """ Notification model """
    NOTIFICATION_TYPES = (
        (1, 'Like'),
        (2, 'Follow'),
        (3, 'Comment')
    )
    
    post = models.ForeignKey('base.Post', on_delete=models.CASCADE, related_name='notify_post', blank=True, null=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notify_from_user')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notify_to_user')
    notification_type = models.IntegerField(choices=NOTIFICATION_TYPES)
    text_preview = models.CharField(max_length=120, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    is_seen = models.BooleanField(default=False)
    
    def __str__(self):
        return f'{self.id} | {self.post} | {self.sender} to {self.user} | {self.notification_type} | {self.date} | {self.is_seen}'

social/base/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

social/base/base_api/views.py
from django.contrib.auth.models import User
from rest_framework import viewsets
from base.models import Post
from .serializers import PostSerializer
from .permissions import IsOwnerOrIsStaffOrReadOnly
from django.db.models import Count, Prefetch
from rest_framework.response import Response
from rest_framework.views import APIView


class PostViewSet(viewsets.ModelViewSet):
    serializer_class = PostSerializer
    queryset = Post.objects.annotate(likes_count=Count('likes')).select_related('author')\
                .only('title', 'slug', 'author', 'date_posted', 'author__id')

    permission_classes = (IsOwnerOrIsStaffOrReadOnly,)

social/base/views.py
from typing import Any
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404, redirect
from .models import Post, Comment
from django.http import HttpResponseRedirect
from django.urls import reverse
from notification.models import Notification
# drf
from django.db.models import Prefetch, Count, Exists, Case, When, BooleanField

# Views and Forms
from .forms import CommentForm
from django.views.generic import (
    ListView, DetailView, CreateView,
    UpdateView, DeleteView
)
# Redis  
import redis
from django.conf import settings
from django.views.decorators.cache import cache_page
from django.core.cache import cache

r = redis.Redis(host=settings.REDIS_HOST,
                port=settings.REDIS_PORT,
                db=settings.REDIS_DB)


def postLike(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        notify = Notification.objects.filter(post=post, sender=request.user, notification_type=1)
        notify.delete()
    else:
        post.likes.add(request.user)
        Notification.objects.create(post=post, sender=request.user, user=post.author, notification_type=1)
    
    return HttpResponseRedirect(reverse('base:post-detail', kwargs={'slug': post.slug,
                                                                    'year': post.date_posted.year,
                                                                    'month': post.date_posted.month,
                                                                    'day': post.date_posted.day, 'pk': post.pk}))


class PostListView(ListView):
    model = Post
    template_name = 'base/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5

    def get_queryset(self) -> QuerySet[Any]:
        queryset = super().get_queryset().select_related('author__profile') \
                    .only('title', 'slug', 'content', 'date_posted', 'author__username', 'author__profile__image')

        return queryset

# def load_more_posts(request):
#     page = request.GET.get('page')
#     posts = Post.obejects.order_by('-date_posted').select_related('author__profile') \
#                     .only('title', 'slug', 'content', 'date_posted', 'author__username', 'author__profile__image')
#     html = render_to_string()

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self) -> bool | None:
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self) -> bool | None:
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDetailView(DetailView):
    model = Post
    
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Model:
        year = self.kwargs["year"]
        month = self.kwargs["month"]
        day = self.kwargs["day"]
        slug = self.kwargs["slug"]
        pk = self.kwargs["pk"]
        cache_key = f"post_{year}_{month}_{day}_{slug}_{pk}"
        post = cache.get(cache_key)
        
        if not post:
            post = get_object_or_404(Post.objects.select_related('author__profile')
                                    .only('title', 'slug', 'content', 'date_posted', 'author__profile__image',
                                        'author__username'),
                                    slug=slug, date_posted__year=year,
                                    date_posted__month=month, date_posted__day=day, pk=pk)
            cache.set(cache_key, post, timeout=60*15)
            
        return post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        
        # comments
        comments = post.comments.select_related('username__profile') \
            .only('post_id', 'username__username', 'content', 'created', 'username__profile__image') \
            .filter(active=True)

        context['comments'] = comments
        context['form'] = CommentForm()

        # likes
        likes_connected = post
        liked = False
       # likes_connected = likes_connected.likes.select_relate('author').only().filter(id=self.request.user.id)
        if likes_connected.likes.filter(id=self.request.user.id).exists():
            liked = True

        context['number_of_likes'] = likes_connected.total_likes()
        context['post_is_liked'] = liked

        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        post = self.object = self.get_object()

        if form.is_valid():
            content = form.cleaned_data['content']

            Comment.objects.create(
                username=request.user, content=content, post=post
            )

            if request.user != post.author:
                Notification.objects.create(post=post, sender=request.user, text_preview=content, user=post.author, notification_type=3)

            return redirect('base:post-detail', 
                                slug=post.slug,
                                year=post.date_posted.year,
                                month=post.date_posted.month,
                                day=post.date_posted.day, pk=post.pk
                )

        context = self.get_context_data()
        context['form'] = form
        return self.render(request, reverse('base:post-detail'), context=context)

    def get_queryset(self) -> QuerySet[Any]:
        queryset = super().get_queryset().select_related('author__profile')
            # .prefetch_related('likes')
        return queryset

social/notification/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from notification.models import Notification
from django.contrib.auth.decorators import login_required
from django.db.models import Prefetch
from base.models import Post
from users.models import Profile


@login_required
def showNotifications(request):
    """ All notifications """
    user = request.user
    notifications = Notification.objects.filter(user=user)\
        .select_related('post')\
        .prefetch_related(Prefetch('sender',
                        queryset=User.objects.select_related('profile').only('username', 'profile__image')))\
        .only('post__title', 'post__date_posted', 'post__slug', 'id', 'sender_id', 'notification_type', 'text_preview', 'date')\
        .order_by('-date')
                                
    return render(request, 'base/notifications.html', {'notifications': notifications})

social/base/templates/base/home.html
{% extends "base.html" %}
{% load static %}
{% load cache %}

{% block content %}
    {% for post in posts %}
      {% with author=post.author profile=post.author.profile %}
      <article class="media content-section">
        <img class="rounded-circle article-img" src='{{ profile.image.url }}'>
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ author.get_absolute_url }}">{{ author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content|safe|truncatewords:50|linebreaks }}</p>
          </div>
        </article>
        {% endwith %}
      {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Back</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}
 
      {% if page_obj.has_next %}
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

    {% endif %}
{% endblock content %}

social/base/templates/base/notifications.html
{% extends "base.html" %}

{% block title %} Notifications {% endblock title %}

{% block content %}
{% if notifications|length == 0 %}
    <span class="content-section container">No Notifications</span>
{% endif %}

<div class="col-md-8 m-auto">
    {% for notification in notifications %}
        <div class="card">
            <div class="card-body">
                <img class="rounded-circle article-img" src="{{ notification.sender.profile.image.url }}" alt="image">
                <span class="card-title h4"><a href="{{ notification.sender.get_absolute_url }}" >{{notification.sender}}</a></span>
                <span class="text-muted float-right small">{{ notification.date }}</span>
                <br><br>
                {% if notification.notification_type == 1 %}
                    <p class="card-text"><i>Liked your post</i> "<a href="{{ notification.post.get_absolute_url }}" >{{ notification.post.title }}</a>"</p>
                {% elif notification.notification_type == 2 %}
                    <p class="card-text"><i>Started following you</i></p>
                {% elif notification.notification_type == 3 %}
                    <p><a href="{{ notification.post.get_absolute_url }}" >{{ notification.post.title }}</a></p>
                    <p class="card-text"><i>{{notification.text_preview}}</i></p>
                {% endif %}
            </div>
        </div>
        <br>
    {% endfor %}
    
    <br><br>
    
    </div>
{% endblock content %}

social/base/templates/base/post_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Delete</button>
                <a class="btn btn-outline-secondary" href="{{ post.get_absolute_url }}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

social/base/templates/base/post_detail.html
{% extends "base.html" %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src='{{ object.author.profile.image.url }}'>
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{{ object.author.get_absolute_url }}">{{ object.author }}</a>
            <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
            <strong class="text-secondary">{{ number_of_likes }} like{{ number_of_likes|pluralize }}</strong>
          </div>
          <h2 class="article-title">{{ object.title }}</h2>
          <p class="article-content">{{ object.content|safe }}</p>
        </div>
      </article>
      {% if user.is_authenticated and object.author != request.user %}
        <div class="form-group">
        <form action="{% url "base:post-like" object.id %}" method="POST">
              {% csrf_token %}
              {% if post_is_liked %}
                <button type="submit" name="post_id" value="{{ object.id }}" class="btn btn-outline-info">Unlike</button>
              {% else %}
                <button type="submit" name="post_id" value="{{ object.id }}" class="btn btn-outline-info">Like</button>
              {% endif %}
        </form>
      {% endif %}
          {% if object.author == user %}
            <div>
              <a class="btn btn-outline-primary btn-sm mt-1 mb-1" href="{% url "base:post-update" object.id %}">Update</a>
              <a class="btn btn-outline-danger btn-sm mt-1 mb-1" href="{% url "base:post-delete" object.id %}">Delete</a>
            </div>
          {% endif %}
        </div>
        <!-- Form to leave comment -->
    {% if user.is_authenticated %}
    <div class="row mt-5">
      <div class="col-lg-6 offset-lg-3">
        <h3>Leave a comment</h3>
        <form method='POST'>
          {% csrf_token %}
          <div class="form-group">
            <span class="ml-2"></span>{{ form.content.label_tag }}
            <textarea class="form-control {% if form.content.errors %}is-invalid{% endif %}" id="id_content"
              name="content" rows="4">{{ form.content.value|default:'' }}</textarea>
          </div>
          <button class="btn btn-primary ml-2" type="submit">Reply</button>
        </form>
      </div>
    </div>
  </div>
  {% endif %}
      <!-- List of comments -->
  {% if comments %}
  <div class="row mt-5">
    <div class="col-lg-6 offset-lg-3">
      Comment{{ comments.count|pluralize }}
      <span class="badge badge-dark ml-2">{{ comments.count }}</span>
    </div>
    {% for comment in comments %}
      <div class="col-lg-6 offset-lg-3 mt-2">
        <div class="card p-2">
          <div class="row">
            <div class="col-12">
              <img class="rounded-circle article-img" src='{{ comment.username.profile.image.url }}'>
              <a class="article-title" href="{{ comment.username.get_absolute_url }}">{{ comment.username }}</a>
            </div>
            <div class="col-12">
              <p class="m-1 mt-3">{{ comment.content }}</p>
              <p class="text-right text-muted"><small>{{ comment.created }}</small></p>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  {% endif %}

{% endblock content %}

social/base/templates/base/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">New Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}