social/base/urls.py
from django.urls import path
from .views import (
    PostListView, PostDetailView,
    PostCreateView, PostUpdateView,
    PostDeleteView, postLike
)
from . import views

app_name = 'base'

urlpatterns = [
    # Post
    #  path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('', PostListView.as_view(), name='home'),
    path('post/<slug:slug>/<int:year>/<int:month>/<int:day>/<int:pk>', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    # Like posts
    path('post-like/<int:pk>', views.postLike, name='post-like'),
]

social/notification/urls.py
from django.urls import path
from notification.views import showNotifications

app_name = 'notification'

urlpatterns = [
    path('notifications/', showNotifications, name='notifications')
]

social/social/urls.py
from django.conf import settings
from django.contrib.auth.models import User
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.pagination import PageNumberPagination
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from rest_framework import routers, serializers, viewsets
from base.base_api import views as base_views
from sending_email_app import views as mail_views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from rest_framework_simplejwt.views import TokenVerifyView

# class StandardResultsSetPagination(PageNumberPagination):
#     page_size = 2
#     page_size_query_param = 'page_size'

class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


class UserViewSet(viewsets.ModelViewSet):
    # pagination_class = StandardResultsSetPagination
    queryset = User.objects.all()
    serializer_class = UserSerializer


router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'posts', base_views.PostViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace='base')),
    path('', include('users.urls', namespace='users')),
    path('', include('notification.urls', namespace='notification')),
    path('api/v1/', include(router.urls)),
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('sendmail/', mail_views.sending_mail_to_all, name="sendmail"),

    # Profile/Registration/Login/Logout
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),

    # Change password
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name='registration/change_password_form.html',
                                                                    success_url=reverse_lazy('change_password_done')),
                                                                    name='change_password'),
    path('change-password/done', auth_views.PasswordChangeDoneView.as_view(template_name='registration/change_password_done.html'),
                                                                            name='change_password_done'),
]

if settings.DEBUG:
    # Media
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # Debug Toolbar
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
        ]

social/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('users/', views.user_search, name='users_list'),
    # Профиль других пользователей
    path('users/<username>', views.user_detail, name='user_detail'),
    path('follow/<username>', views.user_follow, name="user_follow"),
]

social/base/models.py
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from ckeditor.fields import RichTextField


class Post(models.Model):
    """ Post model """
    title = models.CharField(max_length=100)
    content = RichTextField(blank=True, null=True)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=250, null=True,
                            unique_for_date='date_posted')
    likes = models.ManyToManyField(User, related_name='post_like', blank=True)
    
    def total_likes(self):
        return self.likes.count()

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(self.title)
        return super(Post, self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("base:post-detail", kwargs={'slug': self.slug,
                                                   'year': self.date_posted.year,
                                                   'month': self.date_posted.month,
                                                   'day': self.date_posted.day,
                                                   'pk': self.pk})
        
    def __str__(self) -> str:
        return f'{self.author}: {self.title}'
    
    class Meta:
        default_related_name = 'posts'
        ordering = ['-date_posted']
        indexes = [
            models.Index(fields=['-date_posted', 'slug'])
        ]
    

class Comment(models.Model):
    """ Comment model """
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        default_related_name = 'comments'
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]

    def __str__(self) -> str:
        return f'Comment by {self.username} on {self.post}' 

social/base/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

social/base/base_api/views.py
from django.contrib.auth.models import User
from rest_framework import viewsets
from base.models import Post
from .serializers import PostSerializer
from .permissions import IsOwnerOrIsStaffOrReadOnly
from django.db.models import Count, Prefetch
from rest_framework.response import Response
from rest_framework.views import APIView


class PostViewSet(viewsets.ModelViewSet):
    serializer_class = PostSerializer
    queryset = Post.objects.annotate(likes_count=Count('likes')).select_related('author')\
                .only('title', 'slug', 'author', 'date_posted', 'author__id')

    permission_classes = (IsOwnerOrIsStaffOrReadOnly,)

social/base/views.py
from typing import Any
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404, redirect
from .models import Post, Comment
from django.http import HttpResponseRedirect
from django.urls import reverse
from notification.models import Notification
# drf
from django.db.models import Prefetch, Count, Exists, Case, When, BooleanField

# Views and Forms
from .forms import CommentForm
from django.views.generic import (
    ListView, DetailView, CreateView,
    UpdateView, DeleteView
)
# Redis  
import redis
from django.conf import settings
from django.views.decorators.cache import cache_page
from django.core.cache import cache

r = redis.Redis(host=settings.REDIS_HOST,
                port=settings.REDIS_PORT,
                db=settings.REDIS_DB)


def postLike(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        notify = Notification.objects.filter(post=post, sender=request.user, notification_type=1)
        notify.delete()
    else:
        post.likes.add(request.user)
        Notification.objects.create(post=post, sender=request.user, user=post.author, notification_type=1)
    
    return HttpResponseRedirect(reverse('base:post-detail', kwargs={'slug': post.slug,
                                                                    'year': post.date_posted.year,
                                                                    'month': post.date_posted.month,
                                                                    'day': post.date_posted.day, 'pk': post.pk}))


class PostListView(ListView):
    model = Post
    template_name = 'base/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5

    def get_queryset(self) -> QuerySet[Any]:
        queryset = super().get_queryset().select_related('author__profile') \
                    .only('title', 'slug', 'content', 'date_posted', 'author__username', 'author__profile__image')

        return queryset

# def load_more_posts(request):
#     page = request.GET.get('page')
#     posts = Post.obejects.order_by('-date_posted').select_related('author__profile') \
#                     .only('title', 'slug', 'content', 'date_posted', 'author__username', 'author__profile__image')
#     html = render_to_string()

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self) -> bool | None:
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self) -> bool | None:
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDetailView(DetailView):
    model = Post
    
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Model:
        year = self.kwargs["year"]
        month = self.kwargs["month"]
        day = self.kwargs["day"]
        slug = self.kwargs["slug"]
        pk = self.kwargs["pk"]
        cache_key = f"post_{year}_{month}_{day}_{slug}_{pk}"
        post = cache.get(cache_key)
        
        if not post:
            post = get_object_or_404(Post.objects.select_related('author__profile')
                                    .only('title', 'slug', 'content', 'date_posted', 'author__profile__image',
                                        'author__username'),
                                    slug=slug, date_posted__year=year,
                                    date_posted__month=month, date_posted__day=day, pk=pk)
            cache.set(cache_key, post, timeout=60*15)
            
        return post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        
        # comments
        comments = post.comments.select_related('username__profile') \
            .only('post_id', 'username__username', 'content', 'created', 'username__profile__image') \
            .filter(active=True)

        context['comments'] = comments
        context['form'] = CommentForm()

        # likes
        likes_connected = post
        liked = False
       # likes_connected = likes_connected.likes.select_relate('author').only().filter(id=self.request.user.id)
        if likes_connected.likes.filter(id=self.request.user.id).exists():
            liked = True

        context['number_of_likes'] = likes_connected.total_likes()
        context['post_is_liked'] = liked

        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        post = self.object = self.get_object()

        if form.is_valid():
            content = form.cleaned_data['content']

            Comment.objects.create(
                username=request.user, content=content, post=post
            )

            if request.user != post.author:
                Notification.objects.create(post=post, sender=request.user, text_preview=content, user=post.author, notification_type=3)

            return redirect('base:post-detail', 
                                slug=post.slug,
                                year=post.date_posted.year,
                                month=post.date_posted.month,
                                day=post.date_posted.day, pk=post.pk
                )

        context = self.get_context_data()
        context['form'] = form
        return self.render(request, reverse('base:post-detail'), context=context)

    def get_queryset(self) -> QuerySet[Any]:
        queryset = super().get_queryset().select_related('author__profile')
            # .prefetch_related('likes')
        return queryset

social/base/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'base/main.css' %}">

    <title>{% block title %}Social Media — Home{% endblock %}</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'base:home' %}">Social Media</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'base:home' %}">Home</a>
              <a href="" class="text-dark">
              {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="">Chat</a>
              <a class="nav-item nav-link" href="{% url "users:users_list" %}">Users</a>
              <a class="nav-item nav-link" href="{% url "notification:notifications" %}">Notifications</a>
              {% endif %}
            </a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url "base:post-create" %}">Create Post</a>
                <a class="nav-item nav-link" href="{% url "profile" %}">Profile</a>
                <a class="nav-item nav-link" href="{% url "logout" %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url "login" %}">Login</a>
                <a class="nav-item nav-link" href="{% url "register" %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
        </div>
      </div>
    </main>
    {% block include_js %}
    {% endblock %}
    <script>
      document.addEventListener('DOMContentLoaded', (event) => {
        // DOM loaded
        {% block domready %}
        {% endblock %}
      })
    </script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>