social/base/urls.py
from django.urls import path
from .views import (
    PostListView, PostDetailView,
    PostCreateView, PostUpdateView,
    PostDeleteView, postLike
)
from . import views

app_name = 'base'

urlpatterns = [
    # Post
    #  path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('', PostListView.as_view(), name='home'),
    path('post/<slug:slug>/<int:year>/<int:month>/<int:day>/<int:pk>', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    # Like posts
    path('post-like/<int:pk>', views.postLike, name='post-like'),
]

social/social/urls.py
from django.conf import settings
from django.contrib.auth.models import User
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.pagination import PageNumberPagination
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from rest_framework import routers, serializers, viewsets
from base.base_api import views as base_views
from sending_email_app import views as mail_views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from rest_framework_simplejwt.views import TokenVerifyView

# class StandardResultsSetPagination(PageNumberPagination):
#     page_size = 2
#     page_size_query_param = 'page_size'

class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


class UserViewSet(viewsets.ModelViewSet):
    # pagination_class = StandardResultsSetPagination
    queryset = User.objects.all()
    serializer_class = UserSerializer


router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'posts', base_views.PostViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace='base')),
    path('', include('users.urls', namespace='users')),
    path('', include('notification.urls', namespace='notification')),
    path('api/v1/', include(router.urls)),
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('sendmail/', mail_views.sending_mail_to_all, name="sendmail"),

    # Profile/Registration/Login/Logout
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),

    # Change password
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name='registration/change_password_form.html',
                                                                    success_url=reverse_lazy('change_password_done')),
                                                                    name='change_password'),
    path('change-password/done', auth_views.PasswordChangeDoneView.as_view(template_name='registration/change_password_done.html'),
                                                                            name='change_password_done'),
]

if settings.DEBUG:
    # Media
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # Debug Toolbar
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
        ]

social/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('users/', views.user_search, name='users_list'),
    # Профиль других пользователей
    path('users/<username>', views.user_detail, name='user_detail'),
    path('follow/<username>', views.user_follow, name="user_follow"),
]

social/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from PIL import Image

def profile_image_upload_path(instance, filename):
    return f"profiles_pics/{instance.user.username[0].lower()}/{filename}"

class Profile(models.Model):
    """ Profile model """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_online = models.BooleanField(default=False)
    image = models.ImageField(default='default.jpg', upload_to=profile_image_upload_path)
    bio = models.CharField(default="", blank=True, null=True, max_length=500)
    date_of_birth = models.DateField(blank=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):

        super(Profile, self).save(*args, **kwargs) 

        img = Image.open(self.image.path)
        
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def __str__(self) -> str:
        return f'{self.user.username}'

 
# Система подписок
class Contact(models.Model):
    """ Contact model """
    user_from = models.ForeignKey(User, related_name='rel_from_set',
                                  on_delete=models.CASCADE)
    user_to = models.ForeignKey(User, related_name='rel_to_set',
                                on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [
            models.Index(fields=['-created'])
        ]

        ordering = ['-created']

    def __str__(self) -> str:
        return f"{self.user_from} follows to {self.user_to}"


# Добавление модели в User динамически
user_model = get_user_model()
user_model.add_to_class('following',
                        models.ManyToManyField(
                            'self', through=Contact,
                            related_name='followers',
                            symmetrical=False
                        ))

social/users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.forms import UserCreationForm


class SearchForm(forms.Form):
    query = forms.CharField(label='Enter username', max_length=100)

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'bio']

social/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import messages
from .forms import UserRegistrationForm, UserUpdateForm, ProfileUpdateForm, SearchForm
from django.contrib.auth.models import User
from base.models import Post
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Contact
from notification.models import Notification
from django.contrib.postgres.search import (SearchVector,
                                            SearchQuery, SearchRank)


@login_required
@require_POST
def user_follow(request, username):

    user = get_object_or_404(User.objects.only('username'), username=username)

    if user:
        contact = Contact.objects.filter(user_from=request.user,
                                            user_to=user).first()

        if contact:
            Notification.objects.filter(notification_type=3, sender=contact.user_from, user=contact.user_to).delete()
            contact.delete()
            messages.success(request, f'You are no longer a subscriber to {user.username}')
        else:
            contact = Contact.objects.create(user_from=request.user,
                                    user_to=user)
            Notification.objects.create(notification_type=2, sender=contact.user_from, user=contact.user_to)
            messages.success(request, f'You have subscribed to {user.username}')

        return HttpResponseRedirect(reverse('users:user_detail', kwargs={'username': username}))


def user_detail(request, username):
    user = get_object_or_404(User.objects.select_related('profile').prefetch_related('followers')
                             .only('username', 'first_name', 'last_name', 'email',
                                                                         'profile__image', 'profile__bio'), username=username)
    posts = Post.objects.filter(author=user).only('title', 'date_posted', 'slug')

    context = {'user': user, 'posts': posts}
    return render(request, 'users/user_detail.html', context)


def user_search(request):
    # Получить все контакты, где текущий пользователь - user_from
    contacts_user_from = Contact.objects.filter(user_from=request.user)

    # Получить все контакты, где текущий пользователь - user_to
    contacts_user_to = Contact.objects.filter(user_to=request.user)

    followers = contacts_user_to.select_related('user_from__profile').only('user_from__profile__image',
                                                                           'user_from__profile__bio',
                                                                           'user_from__first_name',
                                                                           'user_from__last_name',
                                                                           'user_from__username',
                                                                           'user_from__profile__id')

    followers_users = [follower.user_from for follower in followers]

    friends = Contact.objects.filter(user_from=request.user, user_to__in=followers_users).select_related(
        'user_to__profile').only('user_to__profile__image',
                                 'user_to__profile__bio', 'user_to__first_name',
                                 'user_to__last_name', 'user_to__username', 'user_to__profile__id')

    friends_users = [friend.user_to for friend in friends]

    following_contacts = contacts_user_from.select_related('user_to__profile').only('user_to__profile__image',
                                                                         'user_to__profile__bio', 'user_to__first_name',
                                                                         'user_to__last_name', 'user_to__username', 'user_to__profile__id')
    
    following_users = [contact.user_to for contact in following_contacts]

    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = User.objects.filter(username__icontains=query).select_related('profile').only('profile__image', 'profile__bio',
                                                                                         'username', 'first_name', 'last_name')

    context = {'form': form, 'query': query,
               'results': results, 'following_users': following_users,
               'followers': followers_users, 'friends': friends_users}

    return render(request, 'users/users_list.html', context)


def register(request):
    context = {}
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account has been created! Welcome, {username}!')
            return redirect('login')
    else:
        form = UserRegistrationForm()
    context['form'] = form
    return render(request, 'registration/register.html', context)

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                    request.FILES,
                                    instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Account has been updated!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {'u_form': u_form, 'p_form': p_form}
    return render(request, 'users/profile.html', context)

social/users/templates/users/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Profile {{user.username}}{% endblock %}

{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img"
        width="200" height="200" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Profile Info</legend>
              {{ u_form|crispy }}
              {{ p_form|crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Update</button>
              <a class="btn btn-outline-info" href="{% url "change_password" %}">Change Password</a>
          </div>
      </form>
    </div>
{% endblock content %}

social/users/templates/users/user_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Profile {{user.username}}{% endblock %}

{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img"
        width="200" height="200" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
          <p class="text-secondary">{{ user.first_name }} {{ user.last_name }} {{ user.profile.date_of_birth }}</p>
        </div>
        <div class="form-group">
          <form action="{% url "users:user_follow" user.username %}" method="POST">
            {% csrf_token %}
            {% if request.user != user %}
              {% if request.user not in user.followers.all %}
                <button type="submit" class="btn btn-outline-info">Subscribe</button>
              {% else %}
                <button type="submit" class="btn btn-outline-danger">Unsubscribe</button>
              {% endif %}
            {% endif %}
          </form>
        </div>
      </div>
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Description</legend>
              <p>{{ user.profile.bio }}</p>
              <legend class="border-bottom mb-4">Posts</legend>
              {% if posts %}
                {% for post in posts %}
                  <a class="article-title" href="{{ post.get_absolute_url }}"><p>{{ post.title }}</p></a>
                {% endfor %}
              {% else %}
                <p>У {{ user.username }} пока нет постов.</p>
              {% endif %}
          </fieldset>
    </div>
{% endblock content %}

social/users/templates/users/users_list.html
{% extends "base.html" %}

{% block title %}Social Media — Users{% endblock %}

{% block content %}

  {% if query %}
    <h1>Search user with username: "{{ query }}"</h1>
    <h3>
        {% with results.count as total_results %}
          Found {{ total_results }} result {{ total_results|pluralize }}
        {% endwith %}
    </h3>
    {% for user in results %}
      <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ user.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ user.get_absolute_url }}">{{ user.username }}</a>
              <small>{{user.last_name }} {{ user.first_name }}</small>
            </div>
            <p>{{ user.profile.bio }}</p>
      </article>
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "users:users_list" %}">Search again</a></p>
  {% else %}
    <h1>Search for users</h1>
    <form method="get">
        {{ form.as_p }}
        <button class="btn btn-info" type="submit">Search</button>
    </form>
  {% endif %}
<br>
    <h1>Friends:</h1>
    {% for user in friends %}
    <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ user.profile.image.url }}">
            <div class="media-body">
              <div class="article-metadata">
                <a class="mr-2" href="{{ user.get_absolute_url }}">{{ user.username }}</a>
                <small>{{user.last_name }} {{ user.first_name }}</small>
              </div>
              <p>{{ user.profile.bio }}</p>
    </article>
      {% empty %}
        <p>Yo have no friends.</p>
  {% endfor %}
<br>
  <h1>Your subscriptions:</h1>
  {% for user in following_users %}
        <article class="media content-section">
              <img class="rounded-circle article-img" src="{{ user.profile.image.url }}">
                <div class="media-body">
                  <div class="article-metadata">
                    <a class="mr-2" href="{{ user.get_absolute_url }}">{{ user.username }}</a>
                    <small>{{user.last_name }} {{ user.first_name }}</small>
                  </div>
                  <p>{{ user.profile.bio }}</p>
        </article>
      {% empty %}
        <p>You have no subscriptions.</p>
  {% endfor %}
<br>
    <h1>People subscribed to you:</h1>
    {% for user in followers %}
    <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ user.profile.image.url }}">
            <div class="media-body">
              <div class="article-metadata">
                <a class="mr-2" href="{{ user.get_absolute_url }}">{{ user.username }}</a>
                <small>{{user.last_name }} {{ user.first_name }}</small>
              </div>
              <p>{{ user.profile.bio }}</p>
    </article>
      {% empty %}
        <p>Yo have no followers.</p>
  {% endfor %}
{% endblock content %}